# Generated by Django 2.2.13 on 2020-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='embed',
            field=models.TextField(),
        ),
    ]
